app:
  ak: AK100523687952
  sk: W1WTYvJpfeH1YpUjTpeFbEx^DnpQ&35L
  app_sign_expire: 60
  run_mode: dev
  http_port: 80
  read_timeout: 60
  write_timeout: 60
  runtime_root_path: runtime/
  log_path: logs/

mysql:
  dbname: shop
  user: test
  password: test
  host: 127.0.0.1:3306
  table_prefix: search_

mongodb:
    dbname: shop
    user: test
    password: test
    host: 127.0.0.1:27017

elasticsearch:
  url: http://127.0.0.1:9200
  user: elastic
  password: test
  bulk_action_num: 1000
  bulk_action_size: 20480
  bulk_workers_num: 10

redis:
  host: 127.0.0.1:27017
  password: test
  max_idle: 30
  max_active: 30
  idle_timeout: 200
