app:
  ak: AK100523687952
  sk: W1WTYvJpfeH1YpUjTpeFbEx^DnpQ&35L
  app_sign_expire: 60
  run_mode: dev
  http_port: 80
  read_timeout: 60
  write_timeout: 60
  runtime_root_path: runtime/
  log_path: logs/

mysql:
  dbname: shop_search


mongodb:

elasticsearch:

redis:
